<!DOCTYPE html>
<html>

<head>
    <title>Prova Promise!</title>
</head>

<body>
    <h1>User List</h1>
    <ul id="userList">

    </ul>
    <script>
        async function getUsers() {
            const response = await fetch('https://jsonplaceholder.typicode.com/users');
            // Ãˆ equivalente a response.then(res => res.json())
            const data = await response.json()

            createUserList(data);
        }

        // Le funzioni async restituiscono una promise, posso gestire l'errore qui
        getUsers()
            .catch(err => console.log('ERRORE!!'));

        function createUserList(users) {
            const userList = document.getElementById('userList');

            for (let user of users) {
                const liElement = document.createElement('li');
                liElement.innerText = `${user.username}, ${user.email}`;

                userList.appendChild(liElement);
            }
        }

    </script>
</body>

</html>